In [1]:
%matplotlib inline
import numpy as np

In [2]:
from dsets import getCandidateInfoList, getCt, LunaDataset
candidateInfo_list = getCandidateInfoList(requireOnDisk_bool=False)
positiveInfo_list = [x for x in candidateInfo_list if x[0]]
diameter_list = [x[1] for x in positiveInfo_list]

In [3]:
print(len(positiveInfo_list))
print(positiveInfo_list[0])

1557
CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(66.58022805, 82.56931698, -110.5421104))


In [4]:
for i in range(0, len(diameter_list), 100):
    print('{:4}  {:4.1f} mm'.format(i, diameter_list[i]))

   0  32.3 mm
 100  18.5 mm
 200  13.7 mm
 300  10.7 mm
 400   8.7 mm
 500   7.6 mm
 600   6.7 mm
 700   6.1 mm
 800   5.6 mm
 900   5.1 mm
1000   4.7 mm
1100   4.3 mm
1200   0.0 mm
1300   0.0 mm
1400   0.0 mm
1500   0.0 mm


In [5]:
for candidateInfo_tup in positiveInfo_list[:10]:
    print(candidateInfo_tup)
for candidateInfo_tup in positiveInfo_list[-10:]:
    print(candidateInfo_tup)
    
for candidateInfo_tup in positiveInfo_list:
    if candidateInfo_tup.series_uid.endswith('565'):
        print(candidateInfo_tup)

CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(66.58022805, 82.56931698, -110.5421104))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(48.23675256, 37.47721004, -98.64208784))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(44.19, 37.79, -107.01))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(40.69, 32.19, -97.15))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.44242293, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.943403138251347598519939390311', center_xyz=(-45.29440163, 74.86925386, -97.52812481))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.

In [6]:
np.histogram(diameter_list)

(array([384, 550, 281, 117,  78,  59,  42,  34,   8,   4], dtype=int64),
 array([ 0.        ,  3.22700302,  6.45400605,  9.68100907, 12.9080121 ,
        16.13501512, 19.36201815, 22.58902117, 25.8160242 , 29.04302722,
        32.27003025]))

In [7]:
from vis import findPositiveSamples, showCandidate
positiveSample_list = findPositiveSamples()

0 CandidateInfoTuple(isNodule_bool=True, diameter_mm=25.23320204, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.511347030803753100045216493273', center_xyz=(61.41547409, 74.14971568, -214.5145488))
1 CandidateInfoTuple(isNodule_bool=True, diameter_mm=21.58311204, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.905371958588660410240398317235', center_xyz=(108.5371799, 48.2489232, -120.7658948))
2 CandidateInfoTuple(isNodule_bool=True, diameter_mm=19.65387738, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.752756872840730509471096155114', center_xyz=(61.087494, 71.943756, -67.75))
3 CandidateInfoTuple(isNodule_bool=True, diameter_mm=19.65387738, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.752756872840730509471096155114', center_xyz=(56.04935573, 67.07114688, -65.0256435))
4 CandidateInfoTuple(isNodule_bool=True, diameter_mm=18.7832325, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.202811684116768680758082619196', center_xyz=(-83.13367766, -21.91009085, -96.78606865))
5 CandidateInfoTuple(

In [8]:
series_uid = positiveSample_list[11][2]
showCandidate(series_uid)

ds.candidateInfo_list  [CandidateInfoTuple(isNodule_bool=True, diameter_mm=14.62904955, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.534006575256943390479252771547', center_xyz=(58.85159914, -23.59104716, -69.34953976)), CandidateInfoTuple(isNodule_bool=True, diameter_mm=12.80135622, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.534006575256943390479252771547', center_xyz=(-93.71433712, 63.07956243, -95.2925403)), CandidateInfoTuple(isNodule_bool=True, diameter_mm=7.283782817, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.534006575256943390479252771547', center_xyz=(124.4601424, -8.416102, -208.8481248)), CandidateInfoTuple(isNodule_bool=True, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.534006575256943390479252771547', center_xyz=(-93.910973, 63.824128, -98.809998)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.534006575256943390479252771547', center_xyz=(129.8, -18.62, -232.93)), CandidateInfoTuple(isNodule_

<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.534006575256943390479252771547 0 False [0, 1, 2, 3]


In [9]:
series_uid = '1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565'
showCandidate(series_uid)

ds.candidateInfo_list  [CandidateInfoTuple(isNodule_bool=True, diameter_mm=6.378436317, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565', center_xyz=(146.239444, -161.190112, -310.777295)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565', center_xyz=(134.36, -120.31, -274.2)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565', center_xyz=(131.6013998, -160.1748002, -278.1420002)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565', center_xyz=(130.8921763, -102.9688237, -316.8676473)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565', center_xyz=(130.7651507, -151.6850946, -255.8716983)), CandidateInfoTuple(isNodule_bool=

<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565 0 False [0]


In [10]:
series_uid = '1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354'
showCandidate(series_uid)

ds.candidateInfo_list  [CandidateInfoTuple(isNodule_bool=True, diameter_mm=6.720277435, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354', center_xyz=(59.37353653, -157.9943134, -119.056834)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354', center_xyz=(134.955, -168.625, -298.58)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354', center_xyz=(133.8, -195.2, -308.0)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354', center_xyz=(131.4, -177.05, -316.99)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354', center_xyz=(127.76, -141.21, -329.99)), CandidateInfoTuple(isNodule_bool=False, diameter_mm=0.0, series_uid='1.3.6.1.

<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354 0 False [0]


In [11]:
LunaDataset()[0]

(tensor([[[[-630., -693., -803.,  ..., -868., -861., -868.],
           [-696., -626., -719.,  ..., -831., -811., -849.],
           [-793., -651., -588.,  ..., -789., -777., -818.],
           ...,
           [-720., -681., -629.,  ...,  548.,  793.,  975.],
           [-715., -678., -677.,  ...,  942.,  911.,  725.],
           [-681., -653., -690.,  ...,  657.,  468.,  269.]],
 
          [[-595., -679., -705.,  ..., -835., -831., -845.],
           [-755., -716., -725.,  ..., -687., -684., -772.],
           [-838., -798., -771.,  ..., -705., -683., -742.],
           ...,
           [-646., -669., -664.,  ...,  312.,  460.,  591.],
           [-613., -623., -664.,  ...,  852.,  797.,  699.],
           [-629., -618., -677.,  ...,  798.,  557.,  356.]],
 
          [[-806., -841., -851.,  ..., -826., -834., -829.],
           [-873., -903., -902.,  ..., -811., -821., -834.],
           [-873., -916., -903.,  ..., -813., -814., -818.],
           ...,
           [-579., -629., -706.

In [12]:
import numpy as np
import ipyvolume as ipv
V = np.zeros((128,128,128)) # our 3d array
# outer box
V[30:-30,30:-30,30:-30] = 0.75
V[35:-35,35:-35,35:-35] = 0.0
# inner box
V[50:-50,50:-50,50:-50] = 0.25
V[55:-55,55:-55,55:-55] = 0.0
ipv.quickvolshow(V, level=[0.25, 0.75], opacity=0.03, level_width=0.1, data_min=0, data_max=1)


C:\Users\david\anaconda3\envs\torch_with_cuda\Lib\site-packages\ipyvolume\serialize.py:102: RuntimeWarning: invalid value encountered in cast
  subdata[..., i] = ((gradient[i][zindex] / 2.0 + 0.5) * 255).astype(np.uint8)


Container(children=[VBox(children=(HBox(children=(Label(value='levels:'), FloatSlider(value=0.25, max=1.0, ste…

In [13]:
ct = getCt(series_uid)
ipv.quickvolshow(ct.hu_a, level=[0.25, 0.5, 0.9], opacity=0.1, level_width=0.1, data_min=-1000, data_max=1000)

Container(children=[VBox(children=(HBox(children=(Label(value='levels:'), FloatSlider(value=0.25, max=1.0, ste…

# Note: the following visualization doesn't look very good.
It's only included here for completeness. 

In [14]:
import scipy.ndimage.morphology
def build2dLungMask(ct, mask_ndx, threshold_gcc = 0.7):
    dense_mask = ct.hu_a[mask_ndx] > threshold_gcc
    denoise_mask = scipy.ndimage.morphology.binary_closing(dense_mask, iterations=2)
    tissue_mask = scipy.ndimage.morphology.binary_opening(denoise_mask, iterations=10)
    body_mask = scipy.ndimage.morphology.binary_fill_holes(tissue_mask)
    air_mask = scipy.ndimage.morphology.binary_fill_holes(body_mask & ~tissue_mask)

    lung_mask = scipy.ndimage.morphology.binary_dilation(air_mask, iterations=2)

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask


def build3dLungMask(ct):
    air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = mask_list = \
        [np.zeros_like(ct.hu_a, dtype=np.bool) for _ in range(6)]

    for mask_ndx in range(ct.hu_a.shape[0]):
        for i, mask_ary in enumerate(build2dLungMask(ct, mask_ndx)):
            mask_list[i][mask_ndx] = mask_ary

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask

In [15]:
from dsets import getCt
ct = getCt(series_uid)
air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = build3dLungMask(ct)


C:\Users\david\AppData\Local\Temp\ipykernel_10296\3228287895.py:16: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  [np.zeros_like(ct.hu_a, dtype=np.bool) for _ in range(6)]


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [ ]:
bones = ct.hu_a * (ct.hu_a > 1.5)
lungs = ct.hu_a * air_mask
ipv.figure()
ipv.pylab.volshow(bones + lungs, level=[0.17, 0.17, 0.23], data_min=100, data_max=900)
ipv.show()